exclude: ^deprecated-dune-v1-abstractions/
repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v1.0.0
  hooks:
  - id: check-script-has-no-table-name
  - id: check-script-ref-and-source
  - id: dbt-compile
    stages: [push]
  - id: check-model-has-description
    stages: [push]
  - id: check-model-has-meta-keys
    args: ['--meta-keys', 'blockchain', 'project', 'contributors', '--']
    stages: [push]
  - id: check-model-has-properties-file
    stages: [push]


